/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user/login/anonymous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anonymous user login */
        post: operations["UserController_loginAnonymous"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registered user login */
        post: operations["UserController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User registration */
        post: operations["UserController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["UserController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/short-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get users short info */
        get: operations["UserController_getUsersShortInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: operations["UserController_getUserById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user profile by ID */
        get: operations["UserController_getUserProfileById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload and update user avatar */
        put: operations["UserController_updateAvatar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all game rooms */
        get: operations["GameController_getAll"];
        put?: never;
        /** Create a new game room */
        post: operations["GameController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a game room */
        delete: operations["GameController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a game room */
        post: operations["GameController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a room code. Only for owner */
        post: operations["GameController_getCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the ID of the room the user is currently in */
        get: operations["GameController_getMyCurrentGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/validate-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a game room code */
        post: operations["GameController_validateCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/voice-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a token to join the voice channel for a game room */
        get: operations["GameController_getVoiceRoomToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/games/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all completed games summaries for a user */
        get: operations["HistoryController_getGamesByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/games/{gameId}/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated rounds for a specific game */
        get: operations["HistoryController_getRoundsByGameId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/rounds/{roundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get details for a specific round */
        get: operations["HistoryController_getRoundDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnonymousLoginDto: {
            /** @example Guest_123 */
            name: string;
        };
        UserDto: {
            /**
             * @description Unique UUID
             * @example a1b2c3d4-e5f6-7890-1234-567890abcdef
             */
            id: string;
            /**
             * @description User name
             * @example Alex
             */
            name: string;
            /**
             * @description User role
             * @enum {string}
             */
            role: "anonymous" | "registered";
        };
        LoginResponseDto: {
            /**
             * @description JWT token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /** @description User info */
            user: components["schemas"]["UserDto"];
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            /** @example John Doe */
            name: string;
            /** @example john_doe */
            username: string;
            /** @example password123 */
            password: string;
        };
        MeDtoResponse: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example John Doe */
            name: string;
            /**
             * @example registered
             * @enum {string}
             */
            role: "registered" | "anonymous";
            /** @example john_doe */
            username?: string;
            /** @example user@example.com */
            email?: string;
            /** @example https://example.com/avatar.jpg */
            avatarUrl?: string;
        };
        UserShortInfoResponseDto: {
            /** @description User's ID */
            id: string;
            /** @description User's full name */
            name: string;
            /** @description User's internal username */
            username: string;
            /** @description User's avatar URL */
            avatarUrl: string;
        };
        UserProfileDto: {
            /**
             * @description User ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Display name
             * @example John Doe
             */
            name: string;
            /**
             * @description Username
             * @example johndoe123
             */
            username: string;
            /**
             * @description Avatar URL
             * @example https://example.com/avatar.jpg
             */
            avatarUrl: string;
            /**
             * @description Total games played
             * @example 42
             */
            totalGamesPlayed: number;
            /**
             * @description Total wins
             * @example 15
             */
            totalWins: number;
            /**
             * @description Total score
             * @example 1250
             */
            totalScore: number;
        };
        UploadAvatarDto: {
            /**
             * Format: binary
             * @description Avatar
             */
            avatar: string;
        };
        UploadAvatarResponseDto: {
            /** @description New avatar URL */
            newAvatar: string;
        };
        GameSettingsDto: {
            /**
             * @description The name of the game room
             * @example My Awesome Game Room
             */
            name: string;
            /**
             * @description The round time in seconds
             * @example 60
             */
            roundTimeSeconds: number;
            /**
             * @description The points needed to win
             * @example 10
             */
            pointsToWin: number;
            /**
             * @description Whether the game is private
             * @example false
             */
            isPrivate: boolean;
            /**
             * @description The difficulty level of the words used in the game
             * @example medium
             */
            level: string;
            /**
             * @description Whether only owner can start next round
             * @example true
             */
            isOnlyOwnerCanNextRound: boolean;
            /**
             * @description Whether only owner can change word score
             * @example true
             */
            isOnlyOwnerCanChangeScore: boolean;
            language?: "ru" | "en";
        };
        GameResponseDto: {
            /**
             * @description The unique identifier of the game
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            ownerId: string;
            /** @enum {string} */
            status: "LOBBY" | "IN_PROGRESS" | "FINISHED";
            /** @description Current game settings */
            settings: components["schemas"]["GameSettingsDto"];
            playersCount: number;
            createdAt: number;
        };
        CreateGameDto: {
            /**
             * @description The name of the game
             * @example My Awesome Game
             */
            name: string;
            /**
             * @description Whether the game is private or not
             * @default false
             * @example false
             */
            isPrivate: boolean;
            /**
             * @description The round time in seconds
             * @example 60
             */
            roundTimeSeconds: number;
            /**
             * @description The number of points required to win the game
             * @example 30
             */
            pointsToWin: number;
            /**
             * @description The difficulty level of the words used in the game
             * @example medium
             * @enum {string}
             */
            level: "easy" | "medium" | "hard";
            /** @default true */
            isOnlyOwnerCanNextRound: boolean;
            /** @default true */
            isOnlyOwnerCanChangeScore: boolean;
            language?: "ru" | "en";
        };
        CreateGameResponseDto: {
            /**
             * @description The unique identifier of the game
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            ownerId: string;
            /** @enum {string} */
            status: "LOBBY" | "IN_PROGRESS" | "FINISHED";
            /** @description Current game settings */
            settings: components["schemas"]["GameSettingsDto"];
            playersCount: number;
            createdAt: number;
            code: string;
        };
        JoinGameDto: {
            /**
             * @description The unique identifier of the game room.
             * @example a1b2c3d4-e5f6-7890-1234-567890abcdef
             */
            roomId: string;
            code: string;
        };
        GetRoomCodeDto: {
            /**
             * @description The unique identifier of the game room to which the team will be added.
             * @example a1b2c3d4-e5f6-7890-1234-567890abcdef
             */
            roomId: string;
        };
        GetRoomCodeResponseDto: {
            code: string;
        };
        CurrentGameResponseDto: {
            /**
             * @description The unique identifier of the game
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            roomId: string | null;
            /**
             * @description The passcode/code of the private game, if applicable
             * @example 123456
             */
            code?: string | null;
        };
        ValidateCodeDto: {
            code: string;
            /**
             * @description The unique identifier of the game room
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            roomId: string;
        };
        ValidateCodeResponseDto: {
            valid: boolean;
        };
        GetVoiceTokenResponseDto: {
            /**
             * @description The token to join the voice room
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
             */
            token: string;
        };
        ParticipantDisplayDataDto: {
            isRegistered: boolean;
            userId: Record<string, never> | null;
            name: string;
            avatarUrl: string;
        };
        GameSummaryParticipantDto: {
            participantId: string;
            teamId: string;
            score: number;
            displayData: components["schemas"]["ParticipantDisplayDataDto"];
        };
        RoundSummaryDto: {
            id: string;
            roundNumber: number;
            teamId: string;
            guesserParticipantId: string;
        };
        GameSummaryTeamDto: {
            id: string;
            name: string;
        };
        GameSummaryResponseDto: {
            id: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            settings: components["schemas"]["GameSettingsDto"];
            participants: components["schemas"]["GameSummaryParticipantDto"][];
            roundsSummary: components["schemas"]["RoundSummaryDto"][];
            teams: components["schemas"]["GameSummaryTeamDto"][];
        };
        PaginatedGameSummaryResponse: {
            items: components["schemas"]["GameSummaryResponseDto"][];
            total: number;
            limit: number;
            offset: number;
        };
        WordResponseDto: {
            /**
             * @description Word ID
             * @example uuid-word-1
             */
            id: string;
            /**
             * @description The word text
             * @example Apple
             */
            text: string;
            /**
             * @description The word text
             * @example Apple
             */
            score: number;
        };
        ParticipantStatsDto: {
            participantId: string;
            teamId: string;
            scoreAfterRound: number;
        };
        RoundDetailsResponseDto: {
            roundId: string;
            number: number;
            guesserId: string;
            teamId: string;
            /** @description Words for the round */
            words: components["schemas"]["WordResponseDto"][];
            participantsStats: components["schemas"]["ParticipantStatsDto"][];
        };
        PaginatedRoundDetailsResponse: {
            items: components["schemas"]["RoundDetailsResponseDto"][];
            total: number;
            limit: number;
            offset: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UserController_loginAnonymous: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnonymousLoginDto"];
            };
        };
        responses: {
            /** @description The anonymous user has been successfully logged in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    UserController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description The user has been successfully logged in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Bad request. Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. Invalid email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description The user has been successfully registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Bad request. Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict. User with the same email or username already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user info has been successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDtoResponse"];
                };
            };
            /** @description Unauthorized. The user is not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getUsersShortInfo: {
        parameters: {
            query: {
                /** @description Array of user IDs */
                userIds: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The users short info has been successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserShortInfoResponseDto"][];
                };
            };
        };
    };
    UserController_getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user info has been successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserShortInfoResponseDto"];
                };
            };
        };
    };
    UserController_getUserProfileById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user profile has been successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
        };
    };
    UserController_updateAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadAvatarDto"];
            };
        };
        responses: {
            /** @description Avatar has been successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadAvatarResponseDto"];
                };
            };
        };
    };
    GameController_getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns all game rooms. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponseDto"][];
                };
            };
        };
    };
    GameController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameDto"];
            };
        };
        responses: {
            /** @description The game room has been successfully created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGameResponseDto"];
                };
            };
            /** @description Unauthorized. The user must be authenticated to create a game room. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the game room to delete. */
                id: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The game room has been successfully deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden. The user is not the owner of the game room. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The game room with the specified ID was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameController_join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The unique identifier of the game room to join. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGameDto"];
            };
        };
        responses: {
            /** @description Successfully joined the game room. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponseDto"];
                };
            };
            /** @description Forbidden. The user is already in the game room. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The game room with the specified ID was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameController_getCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The unique identifier of the game room to get the code. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetRoomCodeDto"];
            };
        };
        responses: {
            /** @description Code was successfuly sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRoomCodeResponseDto"];
                };
            };
            /** @description Forbidden. The user is not an owner. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The game room with the specified ID was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameController_getMyCurrentGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns roomId or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentGameResponseDto"];
                };
            };
        };
    };
    GameController_validateCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The code and room ID to validate. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateCodeDto"];
            };
        };
        responses: {
            /** @description Returns whether the code is valid for the specified room. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateCodeResponseDto"];
                };
            };
            /** @description The game room with the specified ID was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameController_getVoiceRoomToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the game room. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a token to join the voice channel. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetVoiceTokenResponseDto"];
                };
            };
            /** @description The game room with the specified ID was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HistoryController_getGamesByUserId: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                /** @description The ID of the user whose game history is being requested */
                userId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of game summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGameSummaryResponse"];
                };
            };
        };
    };
    HistoryController_getRoundsByGameId: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of round details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRoundDetailsResponse"];
                };
            };
        };
    };
    HistoryController_getRoundDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Round details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundDetailsResponseDto"];
                };
            };
        };
    };
}
