/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User login */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all game rooms */
        get: operations["GameController_getAll"];
        put?: never;
        /** Create a new game room */
        post: operations["GameController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a game room */
        delete: operations["GameController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a game room */
        post: operations["GameController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a room code. Only for owner */
        post: operations["GameController_getCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the ID of the room the user is currently in */
        get: operations["GameController_getMyCurrentGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/validate-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a game room code */
        post: operations["GameController_validateCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /**
             * @description Name of the user in the game
             * @example Alex
             */
            name: string;
        };
        UserDto: {
            /**
             * @description Unique UUID
             * @example a1b2c3d4-e5f6-7890-1234-567890abcdef
             */
            id: string;
            /**
             * @description User name
             * @example Alex
             */
            name: string;
        };
        LoginResponseDto: {
            /**
             * @description JWT token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /** @description User info */
            user: components["schemas"]["UserDto"];
        };
        MeDtoResponse: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example John Doe */
            name: string;
        };
        GameSettingsDto: {
            /**
             * @description The name of the game room
             * @example My Awesome Game Room
             */
            name: string;
            /**
             * @description The round time in seconds
             * @example 60
             */
            roundTimeSeconds: number;
            /**
             * @description The points needed to win
             * @example 10
             */
            pointsToWin: number;
            /**
             * @description Whether the game is private
             * @example false
             */
            isPrivate: boolean;
            /**
             * @description The difficulty level of the words used in the game
             * @example medium
             */
            level: string;
        };
        GameResponseDto: {
            /**
             * @description The unique identifier of the game
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            ownerId: string;
            /** @enum {string} */
            status: "LOBBY" | "IN_PROGRESS" | "FINISHED";
            /** @description Current game settings */
            settings: components["schemas"]["GameSettingsDto"];
            playersCount: number;
            createdAt: number;
        };
        CreateGameDto: {
            /**
             * @description The name of the game
             * @example My Awesome Game
             */
            name: string;
            /**
             * @description Whether the game is private or not
             * @default false
             * @example false
             */
            isPrivate: boolean;
            /**
             * @description The time limit for each turn in seconds
             * @example 60
             */
            timeLimit: number;
            /**
             * @description The number of points required to win the game
             * @example 30
             */
            pointsToWin: number;
            /**
             * @description The difficulty level of the words used in the game
             * @example medium
             * @enum {string}
             */
            level: "easy" | "medium" | "hard";
        };
        CreateGameResponseDto: {
            /**
             * @description The unique identifier of the game
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            ownerId: string;
            /** @enum {string} */
            status: "LOBBY" | "IN_PROGRESS" | "FINISHED";
            /** @description Current game settings */
            settings: components["schemas"]["GameSettingsDto"];
            playersCount: number;
            createdAt: number;
            code: string;
        };
        JoinGameDto: {
            /**
             * @description The unique identifier of the game room.
             * @example a1b2c3d4-e5f6-7890-1234-567890abcdef
             */
            roomId: string;
            code: string;
        };
        GetRoomCodeDto: {
            /**
             * @description The unique identifier of the game room to which the team will be added.
             * @example a1b2c3d4-e5f6-7890-1234-567890abcdef
             */
            roomId: string;
        };
        GetRoomCodeResponseDto: {
            code: string;
        };
        CurrentGameResponseDto: {
            /**
             * @description The unique identifier of the game
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            roomId: string;
        };
        ValidateCodeDto: {
            code: string;
            /**
             * @description The unique identifier of the game room
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            roomId: string;
        };
        ValidateCodeResponseDto: {
            valid: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description The user has been successfully logged in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user info has been successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDtoResponse"];
                };
            };
        };
    };
    GameController_getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns all game rooms. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponseDto"][];
                };
            };
        };
    };
    GameController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameDto"];
            };
        };
        responses: {
            /** @description The game room has been successfully created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGameResponseDto"];
                };
            };
            /** @description Unauthorized. The user must be authenticated to create a game room. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the game room to delete. */
                id: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The game room has been successfully deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden. The user is not the owner of the game room. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The game room with the specified ID was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameController_join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The unique identifier of the game room to join. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGameDto"];
            };
        };
        responses: {
            /** @description Successfully joined the game room. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponseDto"];
                };
            };
            /** @description Forbidden. The user is already in the game room. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The game room with the specified ID was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameController_getCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The unique identifier of the game room to get the code. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetRoomCodeDto"];
            };
        };
        responses: {
            /** @description Code was successfuly sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRoomCodeResponseDto"];
                };
            };
            /** @description Forbidden. The user is not an owner. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The game room with the specified ID was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameController_getMyCurrentGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns roomId or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentGameResponseDto"];
                };
            };
        };
    };
    GameController_validateCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The code and room ID to validate. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateCodeDto"];
            };
        };
        responses: {
            /** @description Returns whether the code is valid for the specified room. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateCodeResponseDto"];
                };
            };
            /** @description The game room with the specified ID was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
