openapi: 3.0.0
paths:
  /auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '200':
          description: The user has been successfully logged in.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseDto'
      summary: User login
      tags:
        - Auth
  /auth/me:
    get:
      operationId: AuthController_me
      parameters: []
      responses:
        '200':
          description: The current user info has been successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeDtoResponse'
      security:
        - bearer: []
      summary: Get current user info
      tags:
        - Auth
  /games:
    get:
      operationId: GameController_getAll
      parameters: []
      responses:
        '200':
          description: Returns all game rooms.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GameResponseDto'
      summary: Get all game rooms
      tags:
        - Games
    post:
      operationId: GameController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGameDto'
      responses:
        '201':
          description: The game room has been successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateGameResponseDto'
        '401':
          description: Unauthorized. The user must be authenticated to create a game room.
      security:
        - bearer: []
      summary: Create a new game room
      tags:
        - Games
  /games/{id}:
    delete:
      operationId: GameController_delete
      parameters:
        - name: id
          required: true
          in: path
          description: The unique identifier of the game room to delete.
          schema:
            example: a1b2c3d4-e5f6-7890-1234-567890abcdef
      responses:
        '204':
          description: The game room has been successfully deleted.
        '403':
          description: Forbidden. The user is not the owner of the game room.
        '404':
          description: The game room with the specified ID was not found.
      security:
        - bearer: []
      summary: Delete a game room
      tags:
        - Games
  /games/join:
    post:
      operationId: GameController_join
      parameters: []
      requestBody:
        required: true
        description: The unique identifier of the game room to join.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JoinGameDto'
      responses:
        '200':
          description: Successfully joined the game room.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponseDto'
        '403':
          description: Forbidden. The user is already in the game room.
        '404':
          description: The game room with the specified ID was not found.
      security:
        - bearer: []
      summary: Join a game room
      tags:
        - Games
  /games/code:
    post:
      operationId: GameController_getCode
      parameters: []
      requestBody:
        required: true
        description: The unique identifier of the game room to get the code.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetRoomCodeDto'
      responses:
        '200':
          description: Code was successfuly sent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRoomCodeResponseDto'
        '403':
          description: Forbidden. The user is not an owner.
        '404':
          description: The game room with the specified ID was not found.
      security:
        - bearer: []
      summary: Get a room code. Only for owner
      tags:
        - Games
  /games/current:
    get:
      operationId: GameController_getMyCurrentGame
      parameters: []
      responses:
        '200':
          description: Returns roomId or null
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentGameResponseDto'
      security:
        - bearer: []
      summary: Get the ID of the room the user is currently in
      tags:
        - Games
info:
  title: API Docs
  description: API Docs description
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    LoginDto:
      type: object
      properties:
        name:
          type: string
          description: Name of the user in the game
          example: Alex
      required:
        - name
    UserDto:
      type: object
      properties:
        id:
          type: string
          description: Unique UUID
          example: a1b2c3d4-e5f6-7890-1234-567890abcdef
        name:
          type: string
          description: User name
          example: Alex
      required:
        - id
        - name
    LoginResponseDto:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT token
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        user:
          description: User info
          allOf:
            - $ref: '#/components/schemas/UserDto'
      required:
        - accessToken
        - user
    MeDtoResponse:
      type: object
      properties:
        id:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          example: John Doe
      required:
        - id
        - name
    GameSettingsDto:
      type: object
      properties:
        name:
          type: string
          description: The name of the game room
          example: My Awesome Game Room
        roundTimeSeconds:
          type: number
          description: The round time in seconds
          example: 60
        pointsToWin:
          type: number
          description: The points needed to win
          example: 10
        isPrivate:
          type: boolean
          description: Whether the game is private
          example: false
      required:
        - name
        - roundTimeSeconds
        - pointsToWin
        - isPrivate
    GameResponseDto:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the game
          example: 123e4567-e89b-12d3-a456-426614174000
        ownerId:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
        status:
          type: string
          enum:
            - LOBBY
            - IN_PROGRESS
            - FINISHED
        settings:
          description: Current game settings
          allOf:
            - $ref: '#/components/schemas/GameSettingsDto'
        playersCount:
          type: number
        createdAt:
          type: number
      required:
        - id
        - ownerId
        - status
        - settings
        - playersCount
        - createdAt
    CreateGameDto:
      type: object
      properties:
        name:
          type: string
          description: The name of the game
          example: My Awesome Game
        isPrivate:
          type: boolean
          description: Whether the game is private or not
          example: false
          default: false
        timeLimit:
          type: number
          description: The time limit for each turn in seconds
          example: 60
        pointsToWin:
          type: number
          description: The number of points required to win the game
          example: 30
      required:
        - name
        - isPrivate
        - timeLimit
        - pointsToWin
    CreateGameResponseDto:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the game
          example: 123e4567-e89b-12d3-a456-426614174000
        ownerId:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
        status:
          type: string
          enum:
            - LOBBY
            - IN_PROGRESS
            - FINISHED
        settings:
          description: Current game settings
          allOf:
            - $ref: '#/components/schemas/GameSettingsDto'
        playersCount:
          type: number
        createdAt:
          type: number
        code:
          type: string
      required:
        - id
        - ownerId
        - status
        - settings
        - playersCount
        - createdAt
        - code
    JoinGameDto:
      type: object
      properties:
        roomId:
          type: string
          description: The unique identifier of the game room.
          example: a1b2c3d4-e5f6-7890-1234-567890abcdef
        code:
          type: string
      required:
        - roomId
        - code
    GetRoomCodeDto:
      type: object
      properties:
        roomId:
          type: string
          description: >-
            The unique identifier of the game room to which the team will be
            added.
          example: a1b2c3d4-e5f6-7890-1234-567890abcdef
      required:
        - roomId
    GetRoomCodeResponseDto:
      type: object
      properties:
        code:
          type: string
      required:
        - code
    CurrentGameResponseDto:
      type: object
      properties:
        roomId:
          type: string
          description: The unique identifier of the game
          example: 123e4567-e89b-12d3-a456-426614174000
      required:
        - roomId